'use client';

import UIThemeProvider from '@shared/theme/ThemeProvider';
import { Provider } from 'react-redux';

import { SocketProvider } from '@/shared/context/socket/SocketContext';
import { ToastProvider } from '@/shared/context/ToastContext';
import { UIProvider } from '@/shared/context/UIContext';
import { SessionProvider } from '@/shared/hoc/SessionProvider';
import store from '@/store';
import { SnackbarProvider } from 'notistack';
import './globals.css';

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Libre+Bodoni:ital,wght@0,400..700;1,400..700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Libre+Bodoni:ital,wght@0,400..700;1,400..700&display=swap"
          rel="stylesheet"
        />
        {/* <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
          integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        /> */}
        <title>Majik Gift</title>
      </head>
      <body>
        <Provider store={store}>
          <UIThemeProvider>
            <UIProvider>
              <ToastProvider>
                <SocketProvider>
                  <SnackbarProvider maxSnack={3}>
                    <SessionProvider>{children}</SessionProvider>
                  </SnackbarProvider>
                </SocketProvider>
              </ToastProvider>
            </UIProvider>
          </UIThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
